### PR TITLE
Add unique item property keyword.

### PR DESCRIPTION
**Pull request by blainesch**
@epoberezkin my second test is correctly failing, and it should fail, but when I change `valid` to `false`, like I believe it should be, it fails still and I'm not sure why. 

Can you point me in the right direction?

### CODE REVIEW

**Comment by epoberezkin** [comment]
@blainesch can you change it to false so I can see it fail when it shouldn't? How can I say why it fails otherwise?

btw, the implementation of uniqueItems in Ajv can be helpful.

**Comment by blainesch** [comment]
> btw, the implementation of uniqueItems in Ajv can be helpful.

So a `compile` instead of `validate` ? I can try that :D

**Comment by blainesch** [comment]
I pushed the change you were asking for.

**Comment by epoberezkin** [comment]
https://runkit.com/esp/591f1ba7015d6e0012243737 - works here

maybe it's because you have two tests with the same name? not sure. You need to debug.

**Comment by epoberezkin** [comment]
> So a compile instead of validate ? I can try that :D

Yes, implementation can be more more efficient :) (three loops?), but what I meant was that you may find some ideas there and figure out why it's not working here :). Compile vs. validate won't make much difference as you don't need to manipulate the schema - just to iterate the keys...

A more important thing is that it probably should check deep equality rather than by reference, in the same way uniqueItems is specified. If it were to be added to the spec it would definitely be deep equality. Ajv has "equal" function inside (for performance reasons - it's faster than all the libs I saw, probably should be extracted), not sure what is the better way to do here.

**Comment by blainesch** [comment]
Looks like I needed to define it in `spec/schema-tests.spec.js`. It's a wip right now, I'll add some more tests and look into deepEqual as a test case.

**Comment by epoberezkin** [comment]
right, it simply wasn't added to the instance

**Comment by epoberezkin** [comment]
So if you use compile, it will be passed schema (keys), parentSchema and schema compilation context (it). There is it.util. I suggest exposing equal that Ajv uses there (needs change in Ajv) so you can use `it.util.equal` consistently in the implementations (it is used by enum, constant and uniqueItems).

**Comment by blainesch** [comment]
Sweet, how's that? :D

**Comment by blainesch** [comment]
@epoberezkin any update?

**Comment by epoberezkin** [comment]
@blainesch I didn't realise it's finished. Can you add a section in readme please?

**Comment by blainesch** [comment]
Yeah give me a few minutes [:

**Comment by blainesch** [comment]
Thanks!

**Pull request merged**
